name: Conventional Commits

on:
  pull_request:
    branches: [ main ]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,}$'
          error: 'Your commit message must follow the Conventional Commits standard: https://www.conventionalcommits.org'
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
